# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "dz3" ]

permissions:
  contents: read

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install mypy flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          mypy: true
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Allure
      run: |
        sudo apt-get update 
        sudo apt-get install allure
        python -m pip install allure-pytest
    - name: Run tests with unittest
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install allure-pytest
        pytest --alluredir=report/
    - uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      continue-on-error: true
      with:
        allure_results: report
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
    - name: Deploy allure report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}   
    - name: Print github variables
      run: |
                  echo "BUILD_NUMBER is $BUILD_NUMBER"
                  echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
                  echo "Deploying to production server on branch $GITHUB_REF"
    - name: Post the link to the allure report
      if: always()
      uses: Sibz/github-status-action@v1
      with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha || github.sha}}
          target_url: https://agrushaqa.github.io/otus_python_professional_2022_scoring_api/${GITHUB_RUN_NUMBER}